BracketsMessages:
    DifferentBrackets:
        Enabled: false
        Text: 'Player is in a different bracket and cannot be hurt'
    NoPvp:
        Enabled: false
        Text: 'Either you are the player you are attacking is in a NOPVP bracket and bypassed damage'
Brackets:
    Enabled: false
    nopvp:
        levelsIncluded: '1,2,3'
        pvp: false
    lowerTier:
        levelsIncluded: '4,5,6'
        pvp: true