#LevelPoints - Zoon20X
UseLevelPointsCommand: false
CheckUpdates: true

#This is for players running 1.1.9.8 and wanna import old data to the new type (warning you must delete all current player files / the ones of players you wanna import
#as this method will attempt to run the function when a player joins
ImportOldData: false

#MySQL Setup
UseSQL: false

host: "localhost"
port: 3306
username: "root"
database: ""
password: ""

SQLCloseTimer: 15
#by default the sql will close 15 seconds after reconnecting which means it can have more players through 1 connection instead of running 1 connection per player
#Warning this timer should not be used to keep the connection open forever as SQL connections will automatically close
#also another warning i do not personally recommend going above 1 minute on the close timer as there is no need to having it open for that long recommendations below
#Recommended Min & Max
#Min = 10
#Max = 30

#Use LevelPoints Chat
LPSFormat: false
#turning this to true will create a file called formats.yml were you can choose and create different formats for each level MUST Restart if turned to true
Symbol: "✶"

#Use Rank Boosters
RankMultipliers: false
#Turning this to true will create a new file called RankMultipliers.yml where you can give players
#permission nodes for a perma booster, warning this will + with whatever booster they activate
#(rank=3x, active = 4, Current xp multiplier = 7)



#Connected Plugins
WildStacker: false
MythicMobs: false

#Use the in-Built Actionbar
Actionbar: true
ActionBarSize: 30
#Use the in-Built BossBar
ShowOnEXPOnly: false
#this option is used if you would like to show the bossbar only when the player earns exp
ShowTime: 5
#this option is used to say how long the bossbar will stay active

BossBar: false
BossBarColor: BLUE
#Colors to choose from (this is a limitation with spigot / mc and not the plugin itself
#GREEN
#RED
#BLUE
#PURPLE
#PINK
#WHITE
#YELLOW
RequiredItemLore: false #Set weather or not you need a certain level to use x item


GriefPrevention: false


SaveBlockBreaks&Placed: false
SaveKills&Deaths: false



#Default is 6 hours
BoostersTime: 6


Config Version: 1.2.4
#Do NOT CHANGE ^^^
