MySQL:
  Enabled: false
  Data:
    host: "localhost"
    port: 3306
    database: ""
    username: "root"
    password: ""
    table: ""
    ssl: false


TimedEXP:
  Global:
    Enabled: false
    Amount: 2.5
    Time: 200