MySQL:
  Enabled: false
  Data:
    host: "localhost"
    port: 3306
    database: ""
    username: "root"
    password: ""
    table: ""
    ssl: false


Actionbar:
  OnExp:
    Enabled: true
    Message: '&3Level: &b{level} &3|&b {exp}/{required_exp}'

Progressbar:
  MinStep: 1
  MaxStep: 5
  VisualBorder: "§8┃"
  VisualCompletedStep: "§a░"
  VisualUncompletedStep: "§7░"

TimedEXP:
  Global:
    Enabled: false
    Amount: 2.5
    Time: 200

PlaceholderSettings:
  LevelColors:
    Enabled: false
    Colors:
      Red:
        ID: '&c'
        Levels:
          - 1
          - 2
          - 3
          - 4
          - 5
