MySQL:
  Enabled: false
  Data:
    host: "localhost"
    port: 3306
    database: ""
    username: "root"
    password: ""
    table: ""
    ssl: false


Actionbar:
  OnExp:
    Enabled: true
    Message: '&3Level: &b{level} &3|&b {exp}/{required_exp}'

TimedEXP:
  Global:
    Enabled: false
    Amount: 2.5
    Time: 200