file-version: '2'

NetworkShare:
  CrossNetworkStorage:
    Enabled: false
    Address: 127.0.0.1
    Port: 3000
    ServerID:




Progressbar:
  MinStep: 1
  MaxStep: 5
  VisualBorder: "&8┃"
  VisualCompletedStep: "&a░"
  VisualUncompletedStep: "&7░"