name: LevelPoints
version: 3.0.0
main: me.zoon20x.levelpoints.LevelPoints
api-version: 1.17
authors: [ Zoon20X, rgnter]
description: Leveling plugin with custom features
softdepend:
  - WorldGuard
  - PlaceholderAPI
  - MythicMobs
commands:
  adminlps:
    description: Admin help command
    usage: /<command>
    aliases:
      - adminLPS
      - adminLps
      - lpsAdmin
      - lpsadmin
  lps:
    description: Player help command
    usage: /<command>
    aliases:
      - levelPoints
      - levelpoints
      - lpsHelp
